name = "cerate"
author = "doteq"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3833244c54a2efd9a0a217eb3470dc735599c12a894a461233981dfe1979bb6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"
